Repository smartmind-team/thanosql-sdk-python, pull requests merged in 2024-04, with the labels that each got.

#9 build: add ReadTheDocs
  .gitignore
  .readthedocs.yaml
  README.md
  docs/Makefile
  docs/conf.py
  docs/examples.md
  docs/examples/executing_queries.ipynb
  docs/examples/managing_files.ipynb
  docs/examples/managing_query_templates.ipynb
  docs/examples/managing_schemas.ipynb
  docs/examples/managing_table_templates.ipynb
  docs/examples/managing_tables.ipynb
  docs/examples/managing_views.ipynb
  docs/index.md
  docs/make.bat
  docs/requirements.txt
  examples/README.md
  setup.py
  thanosql/resources/__init__.py
Labels: documentation

#5 feat: rearrange parameter order and add checks for query.execute()
  thanosql/resources/_query.py
Labels: improvement

#7 feat: api_url and engine_url setting and checking
  thanosql/_base_client.py
  thanosql/_client.py
Labels: improvement

#8 feat: beautify basemodel repr
  thanosql/resources/_model.py
  thanosql/resources/_query.py
  thanosql/resources/_table.py
  thanosql/resources/_view.py
Labels: improvement

#16 refactor services from attributes to properties for lazy initializati…
  thanosql/__init__.py
  thanosql/_client.py
  thanosql/resources/__init__.py
  thanosql/resources/_model.py
Labels: refactor

#17 Feat/get as df
  docs/examples/executing_queries.ipynb
  docs/examples/managing_tables.ipynb
  tests/test_file.py
  tests/test_query.py
  tests/test_table.py
  thanosql/resources/__init__.py
  thanosql/resources/_query.py
  thanosql/resources/_record.py
  thanosql/resources/_table.py
Labels: feature

#20 fix: add schema to upload and delete file input
  thanosql/resources/_file.py
Labels: improvement

#15 Feat/table from df
  .github/workflows/python-publish.yml
  .pre-commit-config.yaml
  docs/examples/managing_tables.ipynb
  setup.py
  tests/test_table.py
  thanosql/resources/_table.py
Labels: feature

#19 chore: version bump
  .readthedocs.yaml
  docs/Makefile
  docs/conf.py
  docs/examples.md
  docs/index.md
  docs/requirements.txt
  thanosql/_version.py
Labels: ignore-for-release

#24 Fix/file API update
  docs/examples/managing_files.ipynb
  tests/test_file.py
  thanosql/resources/_file.py
Labels: improvement

#18 docs/docstring
  thanosql/_base_client.py
  thanosql/_client.py
  thanosql/resources/_file.py
  thanosql/resources/_query.py
  thanosql/resources/_schema.py
  thanosql/resources/_table.py
  thanosql/resources/_view.py
Labels: documentation

#25 v0.2.2
  docs/examples/managing_files.ipynb
  tests/test_file.py
  thanosql/_base_client.py
  thanosql/_client.py
  thanosql/_version.py
  thanosql/resources/_file.py
  thanosql/resources/_query.py
  thanosql/resources/_schema.py
  thanosql/resources/_table.py
  thanosql/resources/_view.py
Labels: ignore-for-release

#27 feat: better HTTP response handler in ThanoSQLBaseClient._request()
  thanosql/_base_client.py
Labels: refactor
